### ISSUE TITLE
How could we deal with add-ons here?

### ISSUE THREAD

**Issue by swhgoon** [henrikerola/play-vaadin-integration#1]
need play + GWT?
(@_@)

**Comment by henrikerola** [comment]
Using Vaadin addons should be just matter of doing the GWT Java -> JavaScript compilation. I haven't tested with play but this sbt plugin should do it: https://github.com/henrikerola/sbt-vaadin-plugin. It just needs some configuration to get the widgetset compiled into the correct dir.

**Comment by swhgoon** [comment]
You are right. 
 `compileWidgetsets` with `target in compileWidgetsets := ...` in build.sbt
and add `widgetset = ...` to `\conf\application.conf`
DONE:)
ref: `\org\vaadin\playintegration\PlayDeploymentConfiguration.scala`

Thank you~:)
